apiVersion: v1
kind: Service
metadata:
  name: nodeport-juan-quintero
  namespace: namespace-juan-quintero
spec:
  type: NodePort
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80          # Puerto del Servicio
      targetPort: 80    # Puerto del Pod
      nodePort: 30007   # Puerto expuesto en los nodos (puede ser omitido para asignar automáticamente)
