apiVersion: v1
kind: Pod
metadata:
  name: pod-juan-quintero
  namespace: namespace-juan-quintero
spec:
  containers:
  - name: httpd
    image: 590183924888.dkr.ecr.us-east-1.amazonaws.com/repositorio-juan-quintero:latest
    ports:
    - containerPort: 80
 