apiVersion: v1
kind: Service
metadata:
  name: servicio-juan-quintero
  namespace: namespace-juan-quintero
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80